name: main

on:
    push:
        branches: ["main"]

jobs:
    build-dx:
        name: build
        runs-on: rust:latest
        
        steps:
            - uses: actions/checkout@v3
            - run:  cd demo && cargo install dioxus-cli --locked
            - run:  cd demo && dx build --release
            - uses: actions/upload-pages-artifact@v2
              with:
                path: ./demo/docs
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2